### ISSUE TITLE
新版本在Windows下仍然无法Train?

### ISSUE THREAD

**Issue by Vincentzyx** [kwai/DouZero#27]
Log如下
C:\Users\A\Downloads\DouZero-main>python train.py
Found log directory: douzero_checkpoints\douzero
Saving arguments to douzero_checkpoints\douzero/meta.json
Path to meta file already exists. Not overriding meta.
Saving messages to douzero_checkpoints\douzero/out.log
Path to message file already exists. New data will be appended.
Saving logs data to douzero_checkpoints\douzero/logs.csv
Saving logs' fields to douzero_checkpoints\douzero/fields.csv
THCudaCheck FAIL file=..\torch/csrc/generic/StorageSharing.cpp line=258 error=801 : operation not supported
Traceback (most recent call last):
  File "train.py", line 8, in <module>
    train(flags)
  File "C:\Users\A\Downloads\DouZero-main\douzero\dmc\dmc.py", line 138, in train
    actor.start()
  File "E:\Software\miniconda3\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "E:\Software\miniconda3\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "E:\Software\miniconda3\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "E:\Software\miniconda3\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "E:\Software\miniconda3\lib\site-packages\torch\multiprocessing\reductions.py", line 247, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:258

C:\Users\A\Downloads\DouZero-main>Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "E:\Software\miniconda3\lib\multiprocessing\spawn.py", line 116, in spawn_main
    exitcode = _main(fd, parent_sentinel)
  File "E:\Software\miniconda3\lib\multiprocessing\spawn.py", line 126, in _main
    self = reduction.pickle.load(from_parent)
EOFError: Ran out of input

**Comment by daochenzha** [comment]
@Vincentzyx Windows下现在支持evaluate了，但是train还不行。原因是torch不支持tensor在gpu的共享。要想支持可能得改代码结构。
