### ISSUE TITLE
i cannot train by cuda 11.3 win10 gtx1060,how can i do？

### ISSUE THREAD

**Issue by qq782645210** [kwai/DouZero#38]
THCudaCheck FAIL file=..\torch/csrc/generic/StorageSharing.cpp line=249 error=801 : operation not supported
Traceback (most recent call last):
  File "E:\深度学习相关\DouZero相关群资料\模型训练\分布式训练\分布式训练\train.py", line 8, in <module>
    train(flags)
  File "E:\深度学习相关\DouZero相关群资料\模型训练\分布式训练\分布式训练\douzero\dmc\dmc.py", line 202, in train
    actor.start()
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\process.py", line 121, in start
    self._popen = self._Popen(self)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\context.py", line 327, in _Popen
    return Popen(process_obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\popen_spawn_win32.py", line 93, in __init__
    reduction.dump(process_obj, to_child)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\multiprocessing\reduction.py", line 60, in dump
    ForkingPickler(file, protocol).dump(obj)
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python39\lib\site-packages\torch\multiprocessing\reductions.py", line 247, in reduce_tensor
    event_sync_required) = storage._share_cuda_()
RuntimeError: cuda runtime error (801) : operation not supported at ..\torch/csrc/generic/StorageSharing.cpp:249

**Comment by karoka** [comment]
Possible duplicate of #27

**Comment by profection** [comment]
我也是查了很久，win10情况下只有支持tcc的显卡（像tesla这样的专业卡）才可以多进程训练
1060在win10下不支持多进程训练，所以把代码里面的multiprocessing换车threading就行了，你可以试一下
然后你会发现，训练巨慢无比= =
