### ISSUE TITLE
EOFError: Ran out of input

### ISSUE THREAD

**Issue by lingyunQAQ** [kwai/DouZero#70]
Traceback (most recent call last):
  File "/content/drive/MyDrive/DouZero/evaluate.py", line 24, in <module>
    evaluate(args.landlord,
  File "/content/drive/MyDrive/DouZero/douzero/evaluation/simulation.py", line 48, in evaluate
    card_play_data_list = pickle.load(f)
EOFError: Ran out of input

在使用python3 evaluate.py --landlord /baselines/sl/landlord.ckpt  --landlord_up /baselines/sl/landlord_up.ckpt --landlord_down /baselines/sl/landlord_down.ckpt --eval_data eval_data.pkl --num_workers 30 --gpu_device 0
显示的

**Comment by daochenzha** [comment]
@lingyunQAQ 可能evaluation数据有问题，重新跑一遍`python3 generate_eval_data.py`试试

**Comment by lingyunQAQ** [comment]
> @lingyunQAQ 可能evaluation数据有问题，重新跑一遍`python3 generate_eval_data.py`试试
谢谢回复再次尝试下，可以了，上次是99999999，这次生成了100000就正常在跑了，不过暂时啥也没有，这个评估支持checkpoint么
